### ISSUE TITLE
After update to 2123ede, white screen when click edit instance

### ISSUE THREAD

**Issue by KyleUltimate** [RPMTW/RPMLauncher#13]
run in terminal mode this error happens
```
flutter: type 'Null' is not a subtype of type 'int'
flutter: #0      EditInstance_.build (package:RPMLauncher/Screen/Edit.dart:229)
flutter: #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4782)
flutter: #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4665)
flutter: #3      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840)
flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #26     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840)
flutter: #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831)
flutter: #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #34     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840)
flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #36     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #37     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831)
flutter: #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #53     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831)
flutter: #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #65     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4840)
flutter: #78     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #80     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4831)
flutter: #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #86     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:4355)
flutter: #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4643)
flutter: #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4638)
flutter: #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #96     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6195)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3673)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3425)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4690)
```
can confirm that downgrading to 42f0bf6 fix this issue

**Comment by SiongSng** [comment]
因為在這個版本新增了一個格式(關於記錄遊玩時間)，但是你之前的安裝檔仍是舊的格式，重新建立安裝檔即可，之後會寫例外錯誤 防止這種情況出現，感謝回報。
