### ISSUE TITLE
[Bug]: Window is blank on macOS

### ISSUE THREAD

**Issue by SiongSng** [RPMTW/RPMLauncher#237]
### Description of the error

Nothing is displayed, just a blank window
This bug started appearing after version 1.0.6+880
![圖片](https://user-images.githubusercontent.com/48402225/163706357-2054c3d9-c0ea-4188-905b-045901d5f647.png)
### reproduce step

```bash
1. Open RPMLauncher
2. find the bug
```

### expected-behavior

Content can be displayed normally

### RPMLauncher version

1.0.6+892

### What is your operating system?

MacOS (M1)

### RPMLauncher logs

```shell
[2022-04-17 15:01:46.380182] [0] [Unknown Error] Invalid argument(s): Failed to load dynamic library '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib': dlopen(/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib, 0x0001): tried: '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      DiscordRPC.initialize (package:dart_discord_rpc/dart_discord_rpc.dart:107)
<asynchronous suspension>
#3      Data.init (package:rpmlauncher/util/Data.dart:58)
<asynchronous suspension>
#4      run.<anonymous closure> (package:rpmlauncher/main.dart:32)
<asynchronous suspension>
#5      run (package:rpmlauncher/main.dart:28)
<asynchronous suspension>
#6      main (package:rpmlauncher/main.dart:24)
<asynchronous suspension>

[2022-04-17 15:12:33.720755] [0] [Unknown Error] Invalid argument(s): Failed to load dynamic library '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib': dlopen(/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib, 0x0001): tried: '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      DiscordRPC.initialize (package:dart_discord_rpc/dart_discord_rpc.dart:107)
<asynchronous suspension>
#3      Data.init (package:rpmlauncher/util/Data.dart:58)
<asynchronous suspension>
#4      run.<anonymous closure> (package:rpmlauncher/main.dart:32)
<asynchronous suspension>
#5      run (package:rpmlauncher/main.dart:28)
<asynchronous suspension>
#6      main (package:rpmlauncher/main.dart:24)
<asynchronous suspension>

[2022-04-17 15:28:43.430236] [0] [Unknown Error] Invalid argument(s): Failed to load dynamic library '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib': dlopen(/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib, 0x0001): tried: '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      DiscordRPC.initialize (package:dart_discord_rpc/dart_discord_rpc.dart:107)
<asynchronous suspension>
#3      Data.init (package:rpmlauncher/util/Data.dart:58)
<asynchronous suspension>
#4      run.<anonymous closure> (package:rpmlauncher/main.dart:32)
<asynchronous suspension>
#5      run (package:rpmlauncher/main.dart:28)
<asynchronous suspension>
#6      main (package:rpmlauncher/main.dart:24)
<asynchronous suspension>

[2022-04-17 15:29:38.728660] [0] [Unknown Error] Invalid argument(s): Failed to load dynamic library '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib': dlopen(/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib, 0x0001): tried: '/Users/eddychen/Documents/RPMLauncher/data/discord-rpc-library/libdiscord-rpc.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:12)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:23)
#2      DiscordRPC.initialize (package:dart_discord_rpc/dart_discord_rpc.dart:107)
<asynchronous suspension>
#3      Data.init (package:rpmlauncher/util/Data.dart:58)
<asynchronous suspension>
#4      run.<anonymous closure> (package:rpmlauncher/main.dart:32)
<asynchronous suspension>
#5      run (package:rpmlauncher/main.dart:28)
<asynchronous suspension>
#6      main (package:rpmlauncher/main.dart:24)
<asynchronous suspension>

[2022-04-17 15:49:50.311223] [0] [Info] Starting
[2022-04-17 15:49:50.355227] [0] [Info] OS Version: macOS Version 12.3.1 (Build 21E258)
[2022-04-17 15:49:50.579451] [0] [Info] Start Done
[2022-04-17 15:49:55.729666] [0] [Info] Provider Create
[2022-04-17 15:50:00.781425] [1] [Info] Starting
[2022-04-17 15:50:00.800867] [1] [Info] Provider Create
[2022-04-17 15:50:00.821753] [1] [Info] OS Version: macOS Version 12.3.1 (Build 21E258)
[2022-04-17 15:50:01.029067] [1] [Info] Start Done
```

**Comment by SiongSng** [comment]
https://github.com/RPMTW/RPMLauncher/issues/237
