### ISSUE TITLE
[Bug] 不預期的死當

### ISSUE THREAD

**Issue by BennyDioxide** [RPMTW/RPMLauncher#244]
### 描述錯誤

在Manjaro Linux的AUR灌的RPMLauncher中，重複點擊上方功能列，有一定機率死當

https://user-images.githubusercontent.com/80139133/165095031-a11bfce8-9345-417e-9328-569b559ccd36.mp4

### 重現步驟

```bash
1. 先點「問題反饋」
2. 再點「關於RPMLauncher」
```

### 預期行為

介面可正常使用

### RPMLauncher 版本

1.0.6+903

### 您的作業系統是？

Linux

### RPMLauncher 日誌

```shell
[2022-04-25T21:08:34.566247] [1.0.6+903/0] [Info] Starting
[2022-04-25T21:08:34.889368] [1.0.6+903/0] [Info] OS Version: Linux #1 SMP PREEMPT Mon Mar 28 09:16:36 UTC 2022
[2022-04-25T21:08:35.048140] [1.0.6+903/0] [Info] Start Done
[2022-04-25T21:08:55.145358] [1.0.6+903/0] [Flutter Error] Null check operator used on a null value
#0      HeroController.didPop (package:flutter/src/widgets/heroes.dart:796)
#1      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:3152)
#2      _GrowableList.forEach (dart:core-patch/growable_array.dart:416)
#3      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3979)
#4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3932)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4910)
#6      LauncherShortcuts.build.<anonymous closure> (package:rpmlauncher/widget/launcher_shortcuts.dart:25)
#7      CallbackAction.invoke (package:flutter/src/widgets/actions.dart:534)
#8      ActionDispatcher.invokeAction (package:flutter/src/widgets/actions.dart:573)
#9      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:755)
#10     _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:956)
#11     FocusManager._handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:1687)
#12     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:828)
#13     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:875)
#14     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:77)
#15     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76)
#16     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:380)
#17     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:377)
#18     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190)
#19     _rootRun (dart:async/zone.dart:1426)
#20     _CustomZone.run (dart:async/zone.dart:1328)
#21     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#22     _invoke2 (dart:ui/hooks.dart:189)
#23     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
#24     _Channel.push (dart:ui/channel_buffers.dart:132)
#25     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
#26     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:589)
#27     _dispatchPlatformMessage (dart:ui/hooks.dart:89)

[2022-04-25T21:08:57.335559] [1.0.6+903/0] [Info] Closing mod_info_index
[2022-04-25T21:08:57.338309] [1.0.6+903/0] [Unknown Error] Null check operator used on a null value
#0      HeroController.didPop (package:flutter/src/widgets/heroes.dart:796)
#1      _NavigatorPopObservation.notify (package:flutter/src/widgets/navigator.dart:3152)
#2      _GrowableList.forEach (dart:core-patch/growable_array.dart:416)
#3      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3979)
#4      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3932)
#5      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:4910)
#6      Data.init.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rpmlauncher/util/data.dart:88)
#7      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
```

**Comment by SiongSng** [comment]
現在已修復本錯誤
