### ISSUE TITLE
[Bug] No mods loading

### ISSUE THREAD

**Issue by nijahplays** [RPMTW/RPMLauncher#251]
### Description of the error

No mods loaded in the mod updater

### reproduce step

```bash
Use the snap package

Go to the mods section and mods wont appear
```

### expected-behavior

Mods to show

### RPMLauncher version

Snap-Beta

### What is your operating system?

Linux

### RPMLauncher logs

```shell
[2022-05-22T18:19:14.137026] [1.0.6+908/0] [Info] Starting
[2022-05-22T18:19:14.394997] [1.0.6+908/0] [Info] OS Version: Linux #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022
[2022-05-22T18:19:14.492799] [1.0.6+908/0] [Flutter Error] Null check operator used on a null value
#0      Navigator.of (package:flutter/src/widgets/navigator.dart:2561)
#1      showDialog (package:flutter/src/material/dialog.dart:1068)
#2      _MainScreenState.initState.<anonymous closure> (package:rpmlauncher/screen/main_screen.dart:42)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1091)
#5      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864)
#6      _rootRun (dart:async/zone.dart:1418)
#7      _CustomZone.run (dart:async/zone.dart:1328)
#8      _CustomZone.runGuarded (dart:async/zone.dart:1236)
#9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276)
#10     _rootRun (dart:async/zone.dart:1426)
#11     _CustomZone.run (dart:async/zone.dart:1328)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260)
#13     TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:407)
#14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

[2022-05-22T18:19:19.590492] [1.0.6+908/0] [Info] Start Done
[2022-05-22T18:20:14.852599] [1.0.6+908/0] [Info] Provider Created
[2022-05-22T18:20:30.763949] [1.0.6+908/0] [Info] It took 15 Seconds to download Java 17
[2022-05-22T18:21:51.502587] [1.0.6+908/1] [Info] Starting
[2022-05-22T18:21:51.608282] [1.0.6+908/1] [Info] OS Version: Linux #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022
[2022-05-22T18:21:52.866698] [1.0.6+908/1] [Info] Provider Created
[2022-05-22T18:21:56.805805] [1.0.6+908/1] [Info] Start Done
[2022-05-22T18:22:00.971454] [1.0.6+908/1] [Info] Closing mod_info_index
[2022-05-22T18:23:29.263479] [1.0.6+908/1] [Info] Starting
[2022-05-22T18:23:29.363267] [1.0.6+908/1] [Info] OS Version: Linux #1 SMP PREEMPT Mon May 9 07:52:21 UTC 2022
[2022-05-22T18:23:30.764661] [1.0.6+908/1] [Info] Provider Created
[2022-05-22T18:23:30.962308] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:34.559528] [1.0.6+908/1] [Info] Start Done
[2022-05-22T18:23:36.170319] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:36.546151] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:41.725797] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:41.905566] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:47.168985] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:47.356998] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:47.534363] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:47.754343] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:52.972768] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:58.112706] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:58.279243] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:23:58.458704] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:03.642364] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:08.924145] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:09.106386] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:14.292760] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:14.471667] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:19.631263] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:19.781486] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:19.947223] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:25.186511] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:30.428503] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:30.719588] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:30.937115] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>

[2022-05-22T18:24:31.148407] [1.0.6+908/0] [Io Error] FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1383)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:501)
#2      _parseJson (dart:convert-patch/convert_patch.dart:36)
#3      JsonDecoder.convert (dart:convert/json.dart:612)
#4      JsonCodec.decode (dart:convert/json.dart:216)
#5      CurseForgeHandler.checkFingerPrint (package:rpmlauncher/mod/CurseForge/Handler.dart:190)
<asynchronous suspension>
#6      _ModsViewState.getModInfos (package:rpmlauncher/view/Edit/mods_view.dart:254)
<asynchronous suspension>
#7      _spawn (package:flutter/src/foundation/_isolates_io.dart:126)
<asynchronous suspension>
```

**Comment by SiongSng** [comment]
https://github.com/RPMTW/RPMLauncher/commit/19ff94cd796cb2262b5469393a311fe9ee4a8252
