### ISSUE TITLE
模組顯示不同

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/RPMLauncher#92]
**描述錯誤**
模組顯示不同

**重現步驟**
重現觸發這個錯誤的步驟：
1. 開啟 '安裝檔模組畫面'
2. 發現錯誤

**預期行為**
可以顯示出一樣數量的模組

**截圖**
![image](https://user-images.githubusercontent.com/76562059/137469522-f9187a6f-5240-44d9-b833-a3b0aa0091d4.png)

**RPMLauncher 日誌 (請務必填寫，檔案位於 `RPMLauncher資料儲存位置/logs/發生此錯誤時的時間.txt` )**
```
[2021-10-15T17:53:24.020040] [Info] Starting
[2021-10-15T17:53:24.021037] [Info] Start Done
[2021-10-15T17:53:26.205992] [Unknown Error] type 'Null' is not a subtype of type 'String'
#0      Updater.checkForUpdate.getVersionInfo (package:rpmlauncher/Utility/Updater.dart:110)
#1      Updater.checkForUpdate (package:rpmlauncher/Utility/Updater.dart:121)
<asynchronous suspension>

[2021-10-15T17:53:29.536247] [Info] Starting
[2021-10-15T17:53:29.537246] [Info] Start Done
[2021-10-15T17:53:30.253330] [Info] Provider Create
[2021-10-15T17:53:30.576075] [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'

```

*辨識資訊 (請填寫以下資訊):**
 - 作業系統: Windows
 - RPMLauncher 版本 1.0.0.604
**其他說明**
有關於此錯誤的其他說明

**Comment by SiongSng** [comment]
現在還會嗎?

**Comment by SiongSng** [comment]
現在還會有此錯誤嗎？ 我剛才測試正常

**Comment by SiongSng** [comment]
此問題經提出者確認過無問題
![圖片](https://user-images.githubusercontent.com/48402225/140603715-9096f815-0244-47ec-8d65-e34ac2219c6a.png)
