### ISSUE TITLE
開啟安裝檔崩潰

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/RPMLauncher#96]
**描述錯誤**
開啟安裝檔崩潰

**重現步驟**
重現觸發這個錯誤的步驟：
( 範例 ):
1. 開啟 '開啟安裝檔後1.16.5and 1.17.1'
2. 發現錯誤

**預期行為**
可以成功開啟安裝檔出現遊戲畫面

**截圖**
如果可以，請務必上傳截圖，強烈不建議使用手機翻拍

**RPMLauncher 日誌 (請務必填寫，檔案位於 `RPMLauncher資料儲存位置/logs/發生此錯誤時的時間.txt` )**
```
[2021-10-15T23:01:39.823393] [Info] Starting
[2021-10-15T23:01:39.824391] [Info] Start Done
[2021-10-15T23:01:40.543336] [Info] Provider Create
[2021-10-15T23:01:41.045584] [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'
[2021-10-15T23:01:52.515756] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:02:00.077194] [Info] Starting
[2021-10-15T23:02:00.077194] [Info] Start Done
[2021-10-15T23:02:00.085174] [Info] Provider Create
[2021-10-15T23:02:11.829285] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:08:51.030686] [Info] Starting
[2021-10-15T23:08:51.031685] [Info] Start Done
[2021-10-15T23:08:58.211739] [Info] Provider Create
[2021-10-15T23:10:03.462885] [Info] Starting
[2021-10-15T23:10:03.463885] [Info] Start Done
[2021-10-15T23:10:08.295525] [Info] Starting
[2021-10-15T23:10:08.296520] [Info] Start Done
[2021-10-15T23:10:15.559572] [Info] Provider Create
[2021-10-15T23:10:15.885975] [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'
[2021-10-15T23:10:17.094489] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:10:19.389610] [Info] Provider Create
[2021-10-15T23:10:24.544769] [Info] Starting
[2021-10-15T23:10:24.545765] [Info] Start Done
[2021-10-15T23:10:24.552745] [Info] Provider Create
[2021-10-15T23:10:53.270272] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:10:55.613293] [Info] Starting
[2021-10-15T23:10:55.614291] [Info] Start Done
[2021-10-15T23:10:56.345543] [Info] Provider Create
[2021-10-15T23:10:56.453255] [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'
[2021-10-15T23:11:02.152292] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:11:08.800238] [Info] Starting
[2021-10-15T23:11:08.801228] [Info] Start Done
[2021-10-15T23:11:08.808210] [Info] Provider Create
[2021-10-15T23:11:17.792586] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:13:19.785759] [Info] Starting
[2021-10-15T23:13:19.786757] [Info] Start Done
[2021-10-15T23:13:23.705603] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:13:27.180169] [Info] Starting
[2021-10-15T23:13:27.181168] [Info] Start Done
[2021-10-15T23:13:35.527232] [Info] Provider Create
[2021-10-15T23:13:35.835081] [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'
[2021-10-15T23:13:51.065201] [Unknown Error] SocketException: OS Error: 存取被拒。
, errno = 5, port = 0

[2021-10-15T23:13:54.940405] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: [IO Error] type '_GrowableList<dynamic>' is not a subtype of type 'String'\r\nflutter: [Unknown Error] SocketException: OS Error: 摮?鋡急???\r\n, errno = 5, port = 0\r\n\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:14:52.158545] [Info] Starting
[2021-10-15T23:14:52.159545] [Info] Start Done
[2021-10-15T23:14:55.888174] [Flutter Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new InstanceConfig.fromFile (package:rpmlauncher/Model/Instance.dart:310)
#1      new InstanceConfig.fromIntanceDir (package:rpmlauncher/Model/Instance.dart:305)
#2      EditInstance_.instanceConfig (package:rpmlauncher/Screen/Edit.dart:52)
#3      EditInstance_.InstanceSettings (package:rpmlauncher/Screen/Edit.dart:1113)
#4      EditInstance_.build.<anonymous closure> (package:rpmlauncher/Screen/Edit.dart:1050)
#5      _OptionsViewState.build.<anonymous closure> (package:rpmlauncher/View/OptionsView.dart:91)
#6      _StatefulBuilderState.build (package:flutter/src/widgets/basic.dart:7468)
#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588)
#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578)
#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)
#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#17     _rootRun (dart:async/zone.dart:1428)
#18     _CustomZone.run (dart:async/zone.dart:1328)
#19     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#20     _invoke (dart:ui/hooks.dart:150)
#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#22     _drawFrame (dart:ui/hooks.dart:114)

[2021-10-15T23:15:02.679108] [Unknown Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
[2021-10-15T23:15:02.687074] [Flutter Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new InstanceConfig.fromFile (package:rpmlauncher/Model/Instance.dart:310)
#1      new InstanceConfig.fromIntanceDir (package:rpmlauncher/Model/Instance.dart:305)
#2      Instance.config (package:rpmlauncher/Model/Instance.dart:32)
#3      Instance.name (package:rpmlauncher/Model/Instance.dart:26)
#4      _HomePageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rpmlauncher/main.dart:662)
#5      _MaterialStatePropertyWith.resolve (package:flutter/src/material/material_state.dart:658)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4669)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#22     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:137)
#23     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531)
#24     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:154)
#25     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962)
#26     MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206)
#27     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962)
#28     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#29     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:317)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1852)
#31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
#32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005)
#33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
#34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
#35     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707)
#36     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879)
#37     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497)
#38     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#39     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
#40     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)
#41     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#43     _rootRun (dart:async/zone.dart:1428)
#44     _CustomZone.run (dart:async/zone.dart:1328)
#45     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#46     _invoke (dart:ui/hooks.dart:150)
#47     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#48     _drawFrame (dart:ui/hooks.dart:114)

[2021-10-15T23:15:02.703799] [Unknown Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
[2021-10-15T23:15:02.710791] [Flutter Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
#0      new InstanceConfig.fromFile (package:rpmlauncher/Model/Instance.dart:310)
#1      new InstanceConfig.fromIntanceDir (package:rpmlauncher/Model/Instance.dart:305)
#2      Instance.config (package:rpmlauncher/Model/Instance.dart:32)
#3      Instance.name (package:rpmlauncher/Model/Instance.dart:26)
#4      _HomePageState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rpmlauncher/main.dart:662)
#5      _MaterialStatePropertyWith.resolve (package:flutter/src/material/material_state.dart:658)
#6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4662)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#9      StatelessElement.update (package:flutter/src/widgets/framework.dart:4669)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613)
#12     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#13     StatelessElement.update (package:flutter/src/widgets/framework.dart:4669)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4943)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5626)
#20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6284)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3370)
#22     _LayoutBuilderElement._layout.layoutCallback (package:flutter/src/widgets/layout_builder.dart:137)
#23     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531)
#24     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:154)
#25     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962)
#26     MouseTracker._deviceUpdatePhase (package:flutter/src/rendering/mouse_tracker.dart:206)
#27     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962)
#28     RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:228)
#29     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:317)
#30     RenderObject.layout (package:flutter/src/rendering/object.dart:1852)
#31     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171)
#32     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1005)
#33     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240)
#34     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403)
#35     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707)
#36     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879)
#37     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497)
#38     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883)
#39     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)
#40     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)
#41     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)
#42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)
#43     _rootRun (dart:async/zone.dart:1428)
#44     _CustomZone.run (dart:async/zone.dart:1328)
#45     _CustomZone.runGuarded (dart:async/zone.dart:1236)
#46     _invoke (dart:ui/hooks.dart:150)
#47     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)
#48     _drawFrame (dart:ui/hooks.dart:114)

[2021-10-15T23:15:07.375888] [Unknown Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
[2021-10-15T23:15:07.405250] [Unknown Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'
[2021-10-15T23:15:08.519729] [Info] Starting
[2021-10-15T23:15:08.521726] [Info] Start Done
[2021-10-15T23:15:10.466831] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:15:32.912996] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Flutter Error] type '_TwoByteString' is not a subtype of type 'Map<dynamic, dynamic>'\r\n#0      new InstanceConfig.fromFile (package:rpmlauncher/Model/Instance.dart:310)\r\n#1      new InstanceConfig.fromIntanceDir (package:rpmlauncher/Model/Instance.dart:305)\r\n#2      EditInstance_.instanceConfig (package:rpmlauncher/Screen/Edit.dart:52)\r\n#3      EditInstance_.InstanceSettings (package:rpmlauncher/Screen/Edit.dart:1113)\r\n#4      EditInstance_.build.<anonymous closure> (package:rpmlauncher/Screen/Edit.dart:1050)\r\n#5      _OptionsViewState.build.<anonymous closure> (package:rpmlauncher/View/OptionsView.dart:91)\r\n#6      _StatefulBuilderState.build (package:flutter/src/widgets/basic.dart:7468)\r\n#7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705)\r\n#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4588)\r\n#9      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4763)\r\n#10     Element.rebuild (package:flutter/src/widgets/framework.dart:4311)\r\n#11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2578)\r\n#12     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882)\r\n#13     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363)\r\n#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145)\r\n#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082)\r\n#16     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996)\r\n#17     _rootRun (dart:async/zone.dart:1428)\r\n#18     _CustomZone.run (dart:async/zone.dart:1328)\r\n#19     _CustomZone.runGuarded (dart:async/zone.dart:1236)\r\n#20     _invoke (dart:ui/hooks.dart:150)\r\n#21     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270)\r\n#22     _drawFrame (dart:ui/hooks.dart:114)\r\n\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')
[2021-10-15T23:16:00.870941] [Unknown Error] Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1108)
#1      MinecraftClientHandler.Install.<anonymous closure> (package:rpmlauncher/Launcher/MinecraftClient.dart:148)
#2      DownloadInfos.downloadAll.onDone (package:rpmlauncher/Model/DownloadInfo.dart:36)
#3      DownloadInfos.downloadAll.<anonymous closure> (package:rpmlauncher/Model/DownloadInfo.dart:49)
<asynchronous suspension>
#4      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1281)
<asynchronous suspension>

[2021-10-15T23:16:06.505611] [Info] Starting
[2021-10-15T23:16:06.506615] [Info] Start Done
[2021-10-15T23:16:06.514131] [Info] Provider Create
[2021-10-15T23:16:06.703315] [Unknown Error] FormatException: Unexpected extension byte (at offset 0)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)
#5      _rootRunUnary (dart:async/zone.dart:1436)
#6      _CustomZone.runUnary (dart:async/zone.dart:1335)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#11     _StreamController._add (dart:async/stream_controller.dart:607)
#12     _StreamController.add (dart:async/stream_controller.dart:554)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:2280)
#14     _rootRunUnary (dart:async/zone.dart:1444)
#15     _CustomZone.runUnary (dart:async/zone.dart:1335)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)
#20     _StreamController._add (dart:async/stream_controller.dart:607)
#21     _StreamController.add (dart:async/stream_controller.dart:554)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1808)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1292)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:40)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)

[2021-10-15T23:16:09.394844] [Unknown Error] NoSuchMethodError: Class 'String' has no instance method 'transform'.
Receiver: "flutter: [Info] Starting\r\nflutter: [Info] Start Done\r\nflutter: [Info] Provider Create\r\nflutter: [Unknown Error] FormatException: Unexpected extension byte (at offset 0)\r\n#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1893)\r\n#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314)\r\n#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310)\r\n#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72)\r\n#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111)\r\n#5      _rootRunUnary (dart:async/zone.dart:1436)\r\n#6      _CustomZone.runUnary (dart:async/zone.dart:1335)\r\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)\r\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\r\n#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)\r\n#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)\r\n#11     _StreamController._add (dart:async/stream_controller.dart:607)\r\n#12     _StreamController.add (dart:async/stream_controller.dart:554)\r\n#13     _Socket._onData (dart:io-patch/socket_patch.dart:2280)\r\n#14     _rootRunUnary (dart:async/zone.dart:1444)\r\n#15     _CustomZone.runUnary (dart:async/zone.dart:1335)\r\n#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244)\r\n#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341)\r\n#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)\r\n#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733)\r\n#20     _StreamController._add (dart:async/stream_controller.dart:607)\r\n#21     _StreamController.add (dart:async/stream_controller.dart:554)\r\n#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1808)\r\n#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1292)\r\n#24     _microtaskLoop (dart:async/schedule_microtask.dart:40)\r\n#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49)\r\n\r\n"
Tried calling: transform(Instance of 'Utf8Decoder')

```

*辨識資訊 (請填寫以下資訊):**
 - 作業系統: windows
 - RPMLauncher 版本 609
**其他說明**
有關於此錯誤的其他說明

**Comment by jlin53882** [comment]
我剛剛有修改文字，他就會崩潰
只有原本的版本文字就不會

**Comment by jlin53882** [comment]
1.16.5照常崩潰
1.17.1不會，可以正常使用
只是模組顯示量變少

**Comment by SiongSng** [comment]
更新到 610 後還會嗎?
