### ISSUE TITLE
無法安裝模組包

### ISSUE THREAD

**Issue by jlin53882** [RPMTW/RPMLauncher#98]
**描述錯誤**
無法安裝模組包

**重現步驟**
重現觸發這個錯誤的步驟：
( 範例 ):
1. 開啟 '新增模組包 curseforge'
2. 點擊 '.ATR1 最新版本'
3. 發現錯誤

**預期行為**
可以成功下載模組包

**截圖**
![image](https://user-images.githubusercontent.com/76562059/137563989-49d87c57-7337-449d-8c74-00f5129952c2.png)

**RPMLauncher 日誌 (請務必填寫，檔案位於 `RPMLauncher資料儲存位置/logs/發生此錯誤時的時間.txt` )**
```
[2021-10-16T07:25:10.664476] [Info] Starting
[2021-10-16T07:25:10.664476] [Info] Start Done
[2021-10-16T07:25:15.255284] [Info] Provider Create
[2021-10-16T07:25:32.841601] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
[2021-10-16T07:25:32.848584] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
[2021-10-16T07:25:33.059033] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
#0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:206)
#1      new InstanceConfig.fromFile (package:rpmlauncher/Model/Instance.dart:336)
#2      new InstanceConfig.fromIntanceDir (package:rpmlauncher/Model/Instance.dart:303)
#3      Instance.config (package:rpmlauncher/Model/Instance.dart:32)
#4      MinecraftClientHandler.getLib (package:rpmlauncher/Launcher/MinecraftClient.dart:87)
#5      MinecraftClientHandler.Install (package:rpmlauncher/Launcher/MinecraftClient.dart:140)
#6      FabricClient._Ready (package:rpmlauncher/Launcher/Fabric/FabricClient.dart:100)
#7      FabricClient.createClient (package:rpmlauncher/Launcher/Fabric/FabricClient.dart:51)
<asynchronous suspension>
#8      CurseModPackClient._Ready (package:rpmlauncher/Mod/CurseForge/ModPackClient.dart:104)
<asynchronous suspension>
#9      CurseModPackClient.createClient (package:rpmlauncher/Mod/CurseForge/ModPackClient.dart:36)
<asynchronous suspension>

[2021-10-16T07:25:33.260618] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
[2021-10-16T07:25:33.267600] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
[2021-10-16T07:25:33.292005] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.
[2021-10-16T07:25:33.297948] [Unknown Error] LateInitializationError: Local '_config' has not been initialized.

```

*辨識資訊 (請填寫以下資訊):**
 - 作業系統:windows
 - RPMLauncher 版本 610

**其他說明**
有關於此錯誤的其他說明

**Comment by jlin53882** [comment]
![image](https://user-images.githubusercontent.com/76562059/137564159-c10902ff-2a8d-490d-bb54-584307ef5df9.png)
從本機載入模組包也是，都會卡住
